---
title: Miels Bersyla
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  sass_dir: _sass
excerpt_separator: <!--more-->
facebook_app_id: 1745267542200726
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
